version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: hash-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxca
      POSTGRES_DB: postgres  # default DB that will be created
    ports:
      - "5430:5430"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # custom SQL init script

volumes:
  postgres-data:
